name = "employee-db-swift-soft"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[[d1_databases]]
binding = "DB"
database_name = "employee-db"
database_id = "e90ef474-abd7-414f-bf10-2e3c22e987d2" # Placeholder for local dev
